version: '3.8'
services:
  database:
    image: postgres:16.2
    container_name: less_play_db
    environment:
      POSTGRES_DB: "less_play_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./web
    container_name: "less_play_web"
    env_file:
      - web/.env
    depends_on:
      - database
    command: [ "/app/init.sh" ]

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email imenov06@gmail.com --agree-tos --no-eff-email -d imenov.site
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw

    depends_on:
      - nginx

volumes:
  db_data:

