"""empty message

Revision ID: 3551692d08af
Revises: 2714b71ca785
Create Date: 2024-05-11 17:29:07.597758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3551692d08af'
down_revision: Union[str, None] = '2714b71ca785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('game_course_id_fkey', 'game', type_='foreignkey')
    op.drop_column('game', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('game_course_id_fkey', 'game', 'course', ['course_id'], ['id'])
    op.drop_table('chapter')
    # ### end Alembic commands ###
