"""empty message

Revision ID: 4db167b494eb
Revises: 99b7f6021258
Create Date: 2024-05-11 14:08:03.079338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db167b494eb'
down_revision: Union[str, None] = '99b7f6021258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=2048), nullable=False),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course', sa.Column('title', sa.String(length=1024), nullable=False))
    op.add_column('course', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('course', sa.Column('is_life', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_life')
    op.drop_column('course', 'is_active')
    op.drop_column('course', 'title')
    op.drop_table('topic')
    # ### end Alembic commands ###
