"""empty message

Revision ID: aaa2a1fdee04
Revises: e617b37f7df3
Create Date: 2024-05-11 16:17:08.668651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa2a1fdee04'
down_revision: Union[str, None] = 'e617b37f7df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'time_learn',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'time_learn',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
