"""empty message

Revision ID: de2d0cb76e82
Revises: 94890e78203a
Create Date: 2024-05-11 13:23:30.666531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2d0cb76e82'
down_revision: Union[str, None] = '94890e78203a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('role_in_company', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=2048), nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'date_created')
    op.drop_column('user', 'balance')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'email')
    op.drop_column('user', 'role_in_company')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
