"""empty message

Revision ID: e617b37f7df3
Revises: fe38e05e7660
Create Date: 2024-05-11 16:10:25.275786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e617b37f7df3'
down_revision: Union[str, None] = 'fe38e05e7660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('time_learn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'time_learn')
    # ### end Alembic commands ###
